### ISSUE TITLE
Delete a record from Sync doesn't impact Firefox

### ISSUE THREAD

**Issue by ghost** [mozilla-services/syncclient#31]
May not be an issue in syncclient, but if I remove a guid from bookmarks (relaunching command sends me an error about missing guid so it works) doesn't affect Firefox.

Any idea?

**Comment by rfk** [comment]
Firefox manages deleted items in a slightly weird way - rather than deleting the item from sync, it writes a special "tombstone" record for that item.  When other clients sync down the tombstone, they know to delete the item locally.

Unfortunately I'm not sure whether the format of these records is documented anywhere, and I don't know what it is 😞.  Perhaps @rnewman can help, or you can catch some of the client devs in #sync on Mozilla IRC.

**Comment by rnewman** [comment]
Sync records are in one of three states: exists, deleted, or "don't know". Those map to 200, 200, 404.

The closest to official docs on this is the mention of "deleted" here:

https://mozilla-services.readthedocs.io/en/latest/sync/objectformats.html?highlight=Deleted

But I'll see if I can dig up some client references.

**Comment by rnewman** [comment]
It's worth noting that deletion is a property of the _payload_, not the _envelope_, and deletions are themselves encrypted — from the outside a deleted record just looks a little small.

The payload is technically collection/version-dependent, but they all look like this:

```
{"id": "theguidhere", "deleted": true}
```

For example, deleted password record construction on iOS:

https://github.com/mozilla-mobile/firefox-ios/blob/3f0993bb014514a5de56c667703992c01db91e29/Sync/Synchronizers/LoginsSynchronizer.swift#L15

and the inscrutable cleartext accessor on desktop:

https://dxr.mozilla.org/mozilla-central/source/services/sync/modules/record.js#211

This test shows that the body can _technically_ contain anything the collection likes:

https://dxr.mozilla.org/mozilla-central/source/services/sync/tests/unit/test_syncengine_sync.js#313

— perhaps an additional field is needed to figure out which record to delete.

**Comment by ghost** [comment]
@rnewman Thanks for help ;)
